### PR TITLE
UseGraphQLUpload: remove dependency on singleton schema

### LINKED ISSUE #2: Does not work with scoped schema.
When trying to use a scoped schema `app.UseGraphQLUpload<AppSchema>()` throws an exception:  `Cannot resolve schema from root provider..`. This happens because the schema is being fetched within this helper. Instead it could use the same code that is executed in `app.UseGraphQL()`.

I'm going to test this approach and could submit a PR if you are interested.

### PR DESCRIPTION
**Pull request by ruseinov**
This PR removes the hard dependency on schema being a Singleton and introduces the burden of ValueConverter registration to the schema itself. 
Fixes #2

### CODE REVIEW

**Comment by JannikLassahn** [comment]
Thanks! 👍

**Comment by ruseinov** [comment]
@JannikLassahn Let me know when this gets released and under which version. Thanks!

**Comment by epolishko-5am** [comment]
cool

**Comment by JannikLassahn** [comment]
@ruseinov The new version is now listed on Nuget as v0.3.0.

**Pull request merged**
