### PR TITLE
Support for GraphQL .NET 3

### PR DESCRIPTION
**Pull request by ganhammar**
This PR will bring support for GraphQL .NET 3 that currently is in preview bringing both support for System.Text.Json as well as continue to support Newtonsoft.Json. I tried to follow the patterns of GraphQL .NET Server preview.
All tests passes and the sample project runs. I've also tried the changes with a personal project that I just migrated to the preview version of GraphQL.

I don't know if your interested in this PR, but the target branch should probably not be master if so, the preview of GraphQL Server is from develop branch. It would be super nice to get a preview version out on Nuget that works with the preview version of GraphQL .NET.

Thanks!

### CODE REVIEW

**Comment by JannikLassahn** [comment]
First of all, thank you for your work and interest in this little project!
I would very much like to support the next version of GraphQL and publish a preview package.
Given the amount of changes of the PR it'll take me a bit to go through everything (hopefully in the coming days).

**Comment by ganhammar** [comment]
Thanks for showing a interest in the PR!

Fully understood, I might have gone a bit overboard with some changes that isn't fully necessary, especially in the middleware. I could make it more like how it was before except for the parts dependent on JSON functionalities?

**Comment by JannikLassahn** [comment]
So, I looked through your code as well as the implementation of graphql-dotnet server. 
On the one hand I really like the abstraction and separation through the use of IGraphQLUploadRequestDeserializer.
On the other hand, having multiple nuget packages and additional complexity for such a simple library seems over-engineered. Especially considering that the JSON serialization is an implementation detail. Users of this library shouldn't have to worry about any underlying libraries.
Maybe I'm missing an important use case, but I feel like we should have one nuget package that references the appropriate libraries (System.Text.Json for .NET Core 3 and Newtonsoft.Json for everything else).

**Comment by ganhammar** [comment]
Very valid point! I'm trying to find any reason as of why that wouldn't work but can't find one, I think I was to caught up with what the main library and the server was doing to see that.

I'll give it a try and we'll see if it is any where close to your vision :slightly_smiling_face:

**Comment by ganhammar** [comment]
Okay, updated my branch now. Packages is now included based on framework version and the serializer/deserializer to use is determined with preprocessors, I kept the two different test projects so that both paths is tested. Is these changes what you had in mind?

**Comment by JannikLassahn** [comment]
Very nice!
The only thing that still bothers me a little bit is the massive code duplication in the test projects. I don't know if one can use a single test project for multiple frameworks. If not, a base project that is then referenced by the concrete frameworks should suffice.

I know I'm requesting a lot of changes but I just want to keep this project as lean as possible :wink:

**Comment by ganhammar** [comment]
Yeah, I see your point and had the same reflection! I'll investigate options and come up with a suggestion :slightly_smiling_face:

**Comment by ganhammar** [comment]
That was simpler than expected, I merged the two test projects into one and then targeted the two 
different framework versions. It will then test using both frameworks when running the tests.

**Comment by JannikLassahn** [comment]
Thanks very much!

**Comment by ganhammar** [comment]
Thanks for approving! Will you publish a preview version on nuget based on these changes?

**Comment by JannikLassahn** [comment]
Definitely, I got sidetracked researching how to make a proper CI preview version 😄 So many interesting automation processes and possibilities!

**Pull request merged**
